# TODO 配置数据源相关信息

server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petclinic #?servierTimezone=UTC
    username: root
    password: 1234

